<?php

namespace SiSu\CuentaBundle\Repository;

/**
 * ParroquiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParroquiaRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByMunicipioId($municipio_id)
	{
		$query = $this->getEntityManager()->createQuery("
            SELECT parroquia
            FROM SiSuCuentaBundle:Parroquia parroquia
            LEFT JOIN parroquia.municipio municipio
            WHERE municipio.id = :municipio_id
        ")->setParameter('municipio_id', $municipio_id);
	
		return $query->getArrayResult();
	}
}
